name: AGGREGATOR-X
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install puppeteer puppeteer-extra puppeteer-extra-plugin-stealth
      - run: node AGGREGATOR_CORE.js
      - name: Save Data
        run: |
          git config --global user.name 'Bot'
          git config --global user.email 'bot@bot.se'
          git add market-data.json
          git commit -m "Update" || exit 0
          git push
